version: '3.7'

services:
    ldap_server:
        image: osixia/openldap:latest
        container_name: my-openldap-container
        environment:
            LDAP_ORGANISATION: "My Company"
            LDAP_DOMAIN: "mycompany.com"
            LDAP_ADMIN_PASSWORD: "adminpassword"
        ports:
            - "389:389"
            - "636:636"
        command: --copy-service
